# Generated by Django 5.2.10 on 2026-01-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityweather',
            name='city_name',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='cityweather',
            name='synced_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cityweather',
            index=models.Index(fields=['city_name'], name='weather_cit_city_na_2b16fb_idx'),
        ),
        migrations.AddIndex(
            model_name='cityweather',
            index=models.Index(fields=['synced_at'], name='weather_cit_synced__d97b51_idx'),
        ),
    ]
